### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by siddharthist** [graysky2/checkip#6]
I'd like to use your script, and I would love to see more documentation on installation and configuration. Essential questions to have answered: 
 * When I install via the AUR, will there be a default configuration? 
 * Will it detect which mail client I'm using? 
 * Where do I put in my authentication data? 
 * Does this automatically set an interval for itself? How could I do so with `cron`, `systemd`, etc.? 

While I'm sure I will quickly deduce this information myself, it will make this a lot more likely to attract new users.

**Comment by graysky2** [comment]
It should install a pretty complete manpage.

```
% pacman -Ql checkip | grep man
checkip /usr/share/man/
checkip /usr/share/man/man1/
checkip /usr/share/man/man1/checkip.1.gz
```

**Comment by siddharthist** [comment]
I humbly suggest you point users to that documentation in your README, to make your documentation more obvious.

**Comment by graysky2** [comment]
I think most Linux users are familiar with man xxx, no?
